sudo: false

language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

env:
    -
    - LANG=
    - PYTHONIOENCODING=ascii
    - PYTHONIOENCODING=utf-8
    - PYTHONOPTIMIZE=2

install:
    - python setup.py --quiet install

script:
    - python test_pyformat.py
    - pyformat pyformat.py
    - python test_acid.py setup.py

    - pycodestyle pyformat.py
    - pip install pyflakes; pyflakes pyformat.py

after_success:
    - pip install --quiet coverage
    - make coverage

    - pip install --quiet coveralls
    - coveralls
